# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class TulaLatest < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.0/tula-v0.3.0-darwin-arm64.tar.gz"
      sha256 "2a5a9453814eccea0e8c0d07e5f2e2be3f3573e7b9752e881d6cf69e896d37a6"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.0/tula-v0.3.0-darwin-x64.tar.gz"
      sha256 "4ed243e6adbfe850edfbe97d67e18fcc6932f663e790c4c7ff6af61442317d22"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.0/tula-v0.3.0-linux-arm64.tar.gz"
      sha256 "9bcbad5cdc7549a54922c73472814d3e40843943743c327a35fefdb242128468"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.0/tula-v0.3.0-linux-x64.tar.gz"
      sha256 "05a25da9495e8c556c89ca6c66481a9ae548f48400a60b5eb06d22df84376d19"
    end
  end

  conflicts_with "tula", because: "both install a tula binary"

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
