# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class TulaLatest < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.1/tula-v0.1.1-darwin-arm64.tar.gz"
      sha256 "99f1c50f5fde16f128f85229a6d771228e087f6cdd024f317b77a801639d6cb9"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.1/tula-v0.1.1-darwin-x64.tar.gz"
      sha256 "c992311634073a5f11ec9da3917d8eb7163f44d533f9c2e9f6758a95c73746d5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.1/tula-v0.1.1-linux-arm64.tar.gz"
      sha256 "b501278a29ab97ab8e1461a72e50cb4bf58603770512b4d24003122d771ca181"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.1/tula-v0.1.1-linux-x64.tar.gz"
      sha256 "93b1026b75448c7100dc3894aab3cf42349f9b18467770f06fe01fefafc6fa30"
    end
  end

  conflicts_with "tula", because: "both install a tula binary"

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
