# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Tula < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.3.2"
  license "MIT"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.2/tula-v0.3.2-darwin-arm64.tar.gz"
      sha256 "860655ed2d9a6674c55021908b3bdb03db5584945e47efa915b422c20afdaa72"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.2/tula-v0.3.2-darwin-x64.tar.gz"
      sha256 "8c94433456c66b3c4264ba236665792562fd7d62ffe587cb2869cf803be4dd8d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.2/tula-v0.3.2-linux-arm64.tar.gz"
      sha256 "c26190217c0a030b957ed09740a6bbeb48053c3bd29a935dfe94627481857f9a"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.2/tula-v0.3.2-linux-x64.tar.gz"
      sha256 "32970d3f2a5b441a2d86580452e48a19779085dc4844231a774d4a70675c547f"
    end
  end

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
