# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class TulaLatest < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.2.0/tula-v0.2.0-darwin-arm64.tar.gz"
      sha256 "0cf7785f4430c92c91e1b139c92535b74b685056f1c569fff08ab1ee4f113515"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.2.0/tula-v0.2.0-darwin-x64.tar.gz"
      sha256 "cdb1a7eb9ce28d03e0cb9df957ea0509dd65d66de2583f2faf05e966008fc544"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.2.0/tula-v0.2.0-linux-arm64.tar.gz"
      sha256 "60d356f552f90a7a33e603eb6c1c23b32814e3770ee2974a35f988413d17b478"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.2.0/tula-v0.2.0-linux-x64.tar.gz"
      sha256 "971575b49a474fe9c9c3928e416d4ecc0c5083abb31bbf53a34eefc6dba98c5a"
    end
  end

  conflicts_with "tula", because: "both install a tula binary"

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
