# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Tula < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.3.3"
  license "MIT"

  on_macos do
    depends_on macos: :ventura
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.3/tula-v0.3.3-darwin-arm64.tar.gz"
      sha256 "52bd3deed0fa97cf1072af4dbec9efc10f9581b45f171d10e11065b55c5cd184"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.3/tula-v0.3.3-darwin-x64.tar.gz"
      sha256 "cdf7bdd86047aa37888add2c2d61755dbb057c3cb6e29de576e0f93fa236f2b3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.3/tula-v0.3.3-linux-arm64.tar.gz"
      sha256 "3dd91d7cc0b3003fae61582b25535005652f74a190ee6361cdea0e5f87fad71d"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.3.3/tula-v0.3.3-linux-x64.tar.gz"
      sha256 "d4039d7ab28df2a94d544e2cc964ea2dbea11e0a44ed507d0e1d7792361abc46"
    end
  end

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
