# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class Tula < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.0/tula-v0.1.0-darwin-arm64.tar.gz"
      sha256 "ce8d193b2e310b9f29847460674c0994be1881b29880e2b5d8b07f355fd43392"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.0/tula-v0.1.0-darwin-x64.tar.gz"
      sha256 "7ec3ee229062a7f0b1f879b8ef82143c2e9aa395370e5fc43357c5a589014941"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.0/tula-v0.1.0-linux-arm64.tar.gz"
      sha256 "6a3dba2cc7face3d29cbbaf1da173e816568c3e891e65ecc845ee5196825ae33"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.0/tula-v0.1.0-linux-x64.tar.gz"
      sha256 "e9928f6c678947f2d00588b75638a9142ed9ffdebeb4fb595cdc4c392ad4d8ed"
    end
  end

  conflicts_with "tula-latest", because: "both install a tula binary"

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
