# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class TulaAT012 < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.2/tula-v0.1.2-darwin-arm64.tar.gz"
      sha256 "49e18847addeb27bf879134e1dcf7b0beba95249919e07c9c44d2c6492c64dec"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.2/tula-v0.1.2-darwin-x64.tar.gz"
      sha256 "179ab44a28c10de9e9c780a580e890c115dc3aa3ae079c9ad5819b394122a888"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.2/tula-v0.1.2-linux-arm64.tar.gz"
      sha256 "c3386852d8830feedffd428bb06d33ba5182bcc8ffb720e7aa9f7fa56c96a9e8"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.2/tula-v0.1.2-linux-x64.tar.gz"
      sha256 "803a5c9802ea8d009f2ba2fb63486cf125eb49b9b308f7585fc2398373edd2ef"
    end
  end

  keg_only :versioned_formula

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
