# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class TulaAT013 < Formula
  desc "Your true exposure, what breaks first, and more, across every venue at once."
  homepage "https://usetu.la"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.3/tula-v0.1.3-darwin-arm64.tar.gz"
      sha256 "e79f327397fb7b505cffb341911ced69a7aadf0928ddce652cec1665791a7a9a"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.3/tula-v0.1.3-darwin-x64.tar.gz"
      sha256 "66f8c142328f007a6f190f6007e9f29c5ec19df8dd302ffcad4f9521b20cc1ce"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.3/tula-v0.1.3-linux-arm64.tar.gz"
      sha256 "afb417c36070fa6e21de1162bd9d8e59fcf5b17251fbd4ad13093f9ce49a31d7"
    end
    on_intel do
      url "https://github.com/hsnice16/tula/releases/download/v0.1.3/tula-v0.1.3-linux-x64.tar.gz"
      sha256 "9d140260ca1e91644aede3f68d1296cd40747b3c62652d654860c3c4bc0c35ac"
    end
  end

  keg_only :versioned_formula

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
